# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/spacemaster09/code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/spacemaster09/code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spacemaster09/code/CMakeFiles /home/spacemaster09/code/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spacemaster09/code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named object

# Build rule for target.
object: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 object
.PHONY : object

# fast build rule for target.
object/fast:
	$(MAKE) -f CMakeFiles/object.dir/build.make CMakeFiles/object.dir/build
.PHONY : object/fast

#=============================================================================
# Target rules for targets named object_click

# Build rule for target.
object_click: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 object_click
.PHONY : object_click

# fast build rule for target.
object_click/fast:
	$(MAKE) -f CMakeFiles/object_click.dir/build.make CMakeFiles/object_click.dir/build
.PHONY : object_click/fast

object_detection.o: object_detection.cpp.o
.PHONY : object_detection.o

# target to build an object file
object_detection.cpp.o:
	$(MAKE) -f CMakeFiles/object.dir/build.make CMakeFiles/object.dir/object_detection.cpp.o
.PHONY : object_detection.cpp.o

object_detection.i: object_detection.cpp.i
.PHONY : object_detection.i

# target to preprocess a source file
object_detection.cpp.i:
	$(MAKE) -f CMakeFiles/object.dir/build.make CMakeFiles/object.dir/object_detection.cpp.i
.PHONY : object_detection.cpp.i

object_detection.s: object_detection.cpp.s
.PHONY : object_detection.s

# target to generate assembly for a file
object_detection.cpp.s:
	$(MAKE) -f CMakeFiles/object.dir/build.make CMakeFiles/object.dir/object_detection.cpp.s
.PHONY : object_detection.cpp.s

object_detection_click.o: object_detection_click.cpp.o
.PHONY : object_detection_click.o

# target to build an object file
object_detection_click.cpp.o:
	$(MAKE) -f CMakeFiles/object_click.dir/build.make CMakeFiles/object_click.dir/object_detection_click.cpp.o
.PHONY : object_detection_click.cpp.o

object_detection_click.i: object_detection_click.cpp.i
.PHONY : object_detection_click.i

# target to preprocess a source file
object_detection_click.cpp.i:
	$(MAKE) -f CMakeFiles/object_click.dir/build.make CMakeFiles/object_click.dir/object_detection_click.cpp.i
.PHONY : object_detection_click.cpp.i

object_detection_click.s: object_detection_click.cpp.s
.PHONY : object_detection_click.s

# target to generate assembly for a file
object_detection_click.cpp.s:
	$(MAKE) -f CMakeFiles/object_click.dir/build.make CMakeFiles/object_click.dir/object_detection_click.cpp.s
.PHONY : object_detection_click.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... object"
	@echo "... object_click"
	@echo "... rebuild_cache"
	@echo "... object_detection.o"
	@echo "... object_detection.i"
	@echo "... object_detection.s"
	@echo "... object_detection_click.o"
	@echo "... object_detection_click.i"
	@echo "... object_detection_click.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

